### ISSUE TITLE
Is multi-thread in micropython supported for mx rt1052?

### ISSUE THREAD

**Issue by ianhom** [RockySong/micropython-rocky#1]
Hi, it is great to see this repository, I am trying to port micropython to  **[ShareBoard-iMXRT1050](https://github.com/Share-Board/ShareBoard-iMXRT1050)** recently. 
rt1052 is high-performence  and is perfect for micropython, so I am wondering if multi-thread is supported for rt1052 now?

**Comment by RockySong** [comment]
Not yet, RT-Thread has a multi-threading enabled port, available as on-line packages.

**Comment by ianhom** [comment]
Thanks!
